# <center>Introduction to Numpy</center>
![](http://m.memegen.com/o6i6hi.jpg)

![](https://bids.berkeley.edu/sites/default/files/styles/400x225/public/projects/numpy_project_page.jpg?itok=flrdydei)


# What is Numpy?
---

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays.

It is the fundamental package for scientific computing with Python. It contains among other things:
- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data.
Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

# Installation
---

![](https://i.imgflip.com/21yk3f.jpg)

- **Mac** and **Linux** users can install NumPy via pip command:
    ```
    pip install numpy
    ```

- **Windows** does not have any package manager analogous to that in linux or mac. Please download the pre-built windows installer for NumPy from [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy) (according to your system configuration and Python version). And then install the packages manually.


Once you are done, just type this in python interpreter:
```python
import numpy as np
```

If you are still experiencing some issues, then Stack Overflow is your friend!

If no errors appear,congo! You have successfully installed NumPy. 
Lets move ahead...


## Arrays in NumPy
---
NumPy’s main object is the homogeneous multidimensional array.
- It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
- In NumPy dimensions are called *axes*. The number of axes is *rank*.
- NumPy’s array class is called **ndarray**. It is also known by the alias **array**. 

For example:
```python
[[ 1, 2, 3],
 [ 4, 2, 5]]
```  
This array has:
- rank = 2 (as it is 2-dimensional or it has 2 axes)
- first dimension(axis) length = 2, second dimension has length = 3.
- overall shape can be expressed as: (2, 3)

In [1]:
import numpy as np

In [26]:
a = np.array([[1, 2, 3], [4, 5, 6]], dtype='int32')

In [27]:
a

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [28]:
a.dtype

dtype('int32')

In [5]:
a = np.array([[1, 2, 3], [4, 'jatin', 6]])

In [6]:
a

array([['1', '2', '3'],
       ['4', 'jatin', '6']], dtype='<U21')

![](https://memegenerator.net/img/instances/400x/74259368.jpg)

## Array creation
---
There are various ways to create arrays in NumPy.

- For example, you can create an array from a regular Python **list** or **tuple** using the **array** function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [29]:
l = [[1, 2, 3], [4, 5, 6]]

In [30]:
a = np.array(l)

In [31]:
a

array([[1, 2, 3],
       [4, 5, 6]])

- Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with **initial placeholder content**. These minimize the necessity of growing arrays, an expensive operation. **For example:** np.zeros, np.ones, np.full, np.empty, etc.

In [32]:
a.shape

(2, 3)

In [43]:
a = np.zeros( [2, 3], dtype = 'U16' )

In [44]:
a

array([['', '', ''],
       ['', '', '']], dtype='<U16')

In [38]:
a = np.full( (2, 3), 6 )

In [42]:
a.dtype

dtype('int64')

- To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists.
   - **arange:** returns evenly spaced values within a given interval. **step** size is specified.
   - **linspace:** returns evenly spaced values within a given interval. **num** no. of elements are returned.

In [45]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.linspace(0, 10, 4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

- **Reshaping array:** We can use **reshape** method to reshape an array. Consider an array with shape (a1, a2, a3, ..., aN). We can reshape and convert it into another array with shape (b1, b2, b3, ....., bM). The only required condition is:   <br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*a1 x a2 x a3 .... x aN = b1 x b2 x b3 .... x bM *. (i.e original size of array remains unchanged.)

In [58]:
l = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
]
# 3x4

In [59]:
a = np.array(l)

In [60]:
a.shape

(3, 4)

In [63]:
a.reshape( (2, 2, 3) )
# 2x2x3
# 2x2x3 = 3x4

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

- **Flatten array:** We can use **flatten** method to get a copy of array collapsed into **one dimension**. It accepts *order* argument. Default value is 'C' (for row-major order). Use 'F' for column major order.

In [69]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [71]:
a.flatten(order = 'F')

array([ 1,  5,  9,  2,  6, 10,  3,  7, 11,  4,  8, 12])

## Array Indexing
---

Knowing the basics of array indexing is important for analysing and manipulating the array object.
NumPy offers many ways to do array indexing.

- **Slicing:** Just like lists in python, NumPy arrays can be sliced. As arrays can be multidimensional, you need to specify a slice for each dimension of the array.

In [72]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [77]:
a[-2:, -2:]

array([[ 7,  8],
       [11, 12]])

In [78]:
kernel_size = (2, 2)

In [79]:
step_size = 1

In [83]:
for i in range(a.shape[0] - kernel_size[0] - step_size + 2):
    for j in range(a.shape[1] - kernel_size[1] - step_size + 2):
        kernel = a[i:i+kernel_size[0], j:j+kernel_size[1]]
        
        print(sum(kernel.flatten()))

14
18
22
30
34
38


- **Integer array indexing:** In this method, lists are passed for indexing for each dimension. One to one mapping of corresponding elements is done to construct a new arbitrary array.

In [84]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [85]:
a[[0, 2]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [88]:
a[[0, 2], [1, 3]]

array([ 2, 12])

- **Boolean array indexing:** This method is used when we want to pick elements from array which satisfy some condition.

In [101]:
a[a % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

## Basic operations
---

Plethora of built-in arithmetic functions are provided in NumPy.

- **Operations on single array:** We can use overloaded arithmetic operators to do element-wise operation on array to create a new array. In case of +=, -=, *= operators, the exsisting array is modified.

**Here are some examples:**

In [102]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [103]:
a + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [104]:
a * 2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [106]:
a - 10

array([[-9, -8, -7, -6],
       [-5, -4, -3, -2],
       [-1,  0,  1,  2]])

In [110]:
a > 5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [111]:
b = a+5

In [117]:
b = b.reshape((4, 3))

In [118]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [119]:
a * b

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [120]:
a @ b

array([[120, 130, 140],
       [288, 314, 340],
       [456, 498, 540]])

In [121]:
a.dot(b)

array([[120, 130, 140],
       [288, 314, 340],
       [456, 498, 540]])


- **Unary operators:** Many unary operations are provided as a method of **ndarray** class. This includes sum, min, max, etc. These functions can also be applied row-wise or column-wise by setting an axis parameter.

**Here are some examples:**

In [123]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [122]:
a.max()

12

In [125]:
a.max(axis = 0)

array([ 9, 10, 11, 12])

In [128]:
a.sum(axis = 1)

array([10, 26, 42])

---
- **Binary operators:** These operations apply on array elementwise and a new array is created. You can use all basic arithmetic operators like +, -, /, *, etc. In case of +=, -=, *= operators, the exsisting array is modified.

**Here are some examples:**

In [130]:
a += 5

In [131]:
a

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])


- **Universal functions (ufunc):** NumPy provides familiar mathematical functions such as sin, cos, exp, etc. These functions also operate elementwise on an array, producing an array as output.

**Note:** All the operations we did above using overloaded operators can be done using ufuncs like np.add, np.subtract, np.multiply, np.divide, np.sum, etc.

In [134]:
a = np.array([ 0, np.pi/2, np.pi, (3*np.pi)/2, 2*np.pi ])

In [135]:
np.sin(a)

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16])

## Sorting array
There is a simple **np.sort** method for sorting NumPy arrays.
Let's explore it a bit.

In [138]:
a = np.array([
       [ 5,  6,  7,  8],
        [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [141]:
np.sort(a, axis = None)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

descending sort

# Stacking and Splitting

Several arrays can be stacked together along different axes.

- **np.vstack:** To stack arrays along vertical axis.

- **np.hstack:** To stack arrays along horizontal axis.

- **np.column_stack:** To stack 1-D arrays as columns into 2-D arrays.

- **np.concatenate:** To stack arrays along specified axis (axis is passed as argument).

In [142]:
a = np.full((2, 2), 6)

In [144]:
b  = np.full((2, 2), 5)

In [146]:
np.vstack((a, b))

array([[6, 6],
       [6, 6],
       [5, 5],
       [5, 5]])

In [148]:
c = np.hstack((a, b))

For splitting, we have these fuctions:

- **np.hsplit:** Split array along horizontal axis.

- **np.vsplit:** Split array along vertical axis.

- **np.array_split:** Split array along specified axis.

In [152]:
np.hsplit?

In [161]:
np.vsplit(c, 2)

[array([[6, 6, 5, 5]]), array([[6, 6, 5, 5]])]

# Working with datetime


Numpy has core array data types which natively support datetime functionality. The data type is called “datetime64”, so named because “datetime” is already taken by the datetime library included in Python.

Consider the example below for some examples:

# Linear algebra in NumPy


The **Linear Algebra** module of NumPy offers various methods to apply linear algebra on any numpy array.

You can find:
- rank, determinant, trace, etc. of an array.
- eigen values of matrices
- matrix and vector products (dot, inner, outer,etc. product), matrix exponentiation
- solve linear or tensor equations
and much more!

Now, let us assume that we want to solve this linear equation set:
```
x + 2*y = 8
3*x + 4*y = 18
```
This problem can be solved using **linalg.solve** method as shown in example below:

In [162]:
# coff
cof = np.array([[1, 2], [3, 4]])
# const
con = np.array([8, 18])

In [163]:
np.linalg.solve(cof, con)

array([2., 3.])

In [164]:
def error(y, h):
    return ((y - h)**2).sum() / (2*y.shape[0])

In [167]:
error(np.array([1, 2, 3, 4]), np.array([1, 2, 3, 4]))

0.0

## Saving and loading numpy arrays


The ``.npy`` format is the standard binary file format in NumPy for
persisting a **single** arbitrary NumPy array on disk. The format stores all
of the shape and dtype information necessary to reconstruct the array
correctly even on another machine with a different architecture.
The format is designed to be as simple as possible while achieving
its limited goals.

The ``.npz`` format is the standard format for persisting **multiple** NumPy
arrays on disk. A ``.npz`` file is a zip file containing multiple ``.npy``
files, one for each array.

- **np.save(filename, array)** : saves a single array in ``npy`` format.

- **np.savez(filename, array_1[, array_2])** : saves multiple numpy arrays in ``npz`` format.

- **np.load(filename)** : load a ``npy`` or ``npz`` format file.

In [168]:
a = np.array([1, 2, 3])

In [171]:
np.save("a.npy", a)

References:
- [broadcasting](http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc)
- [datetime in numpy](https://docs.scipy.org/doc/numpy/reference/arrays.datetime.html#arrays-dtypes-dateunits)
- [linaer algebra in numpy](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

![](https://i.pinimg.com/736x/c8/90/b2/c890b24d364d6ae6413c37b70e6640ae--math-jokes-math-humor.jpg)